// projects/examples/react/src/App.tsx
import { useEffect, useState } from 'react';
import './index.css';

function App({ efsdb }: { efsdb?: any }) {
  const [count, setCount] = useState(0);

  useEffect(() => {
    const loader = document.getElementById('efsdb-initial-loader');
    if (loader) {
      loader.style.opacity = '0';
      setTimeout(() => loader.remove(), 300);
    }
  }, []);

  const siteData = {
    title: "EFSDB React Template",
    description: "A cohesive template spreading data from EFSDB.",
    features: [
      "Instant Edge Delivery",
      "React + Vite Integration",
      "Public Workspace Access"
    ]
  };

  return (
    <div className="template-container">
      <header className="hero">
        <h1>{siteData.title}</h1>
        <p className="subtitle">{siteData.description}</p>
      </header>

      <main className="content">
        <section className="features-grid">
          {siteData.features.map((feature, i) => (
            <div key={i} className="feature-card">
              <h3>{feature}</h3>
              <p>Powered by the EFSDB runtime and public workspace.</p>
            </div>
          ))}
        </section>

        <section className="interactive-section">
          <h2>Interactive Counter</h2>
          <p>State is preserved and hydrating works perfectly.</p>
          <button className="action-btn" onClick={() => setCount(count + 1)}>
            Clicked {count} times
          </button>
        </section>

        {efsdb && (
          <section className="interactive-section" style={{ marginTop: '2rem' }}>
            <h2>EFSDB Hydration Data</h2>
            <pre style={{ textAlign: 'left', background: '#f4f4f5', padding: '1rem', borderRadius: '8px', overflowX: 'auto', fontSize: '0.875rem' }}>
              {JSON.stringify(efsdb, null, 2)}
            </pre>
          </section>
        )}
      </main>
    </div>
  );
}

export default App;

// projects/examples/svelte/src/App.svelte
<script lang="ts">
  import { onMount } from 'svelte';
  
  let count = $state(0);

  let efsdbData = $state(null);

  onMount(() => {
    const loader = document.getElementById('efsdb-initial-loader');
    if (loader) {
      loader.style.opacity = '0';
      setTimeout(() => loader.remove(), 300);
    }

    if (typeof window !== 'undefined' && (window as any).__EFSDB__) {
      efsdbData = (window as any).__EFSDB__;
    }
  });

  const siteData = {
    title: "EFSDB Svelte Template",
    description: "A cohesive template spreading data from EFSDB.",
    features: [
      "Instant Edge Delivery",
      "Svelte + Vite Integration",
      "Public Workspace Access"
    ]
  };
</script>

<div class="template-container">
  <header class="hero">
    <h1>{siteData.title}</h1>
    <p class="subtitle">{siteData.description}</p>
  </header>

  <main class="content">
    <section class="features-grid">
      {#each siteData.features as feature}
        <div class="feature-card">
          <h3>{feature}</h3>
          <p>Powered by the EFSDB runtime and public workspace.</p>
        </div>
      {/each}
    </section>

    <section class="interactive-section">
      <h2>Interactive Counter</h2>
      <p>State is preserved and hydrating works perfectly.</p>
      <button class="action-btn" onclick={() => count++}>
        Clicked {count} times
      </button>
    </section>

    {#if efsdbData}
      <section class="interactive-section" style="margin-top: 2rem;">
        <h2>EFSDB Hydration Data</h2>
        <pre style="text-align: left; background: #f4f4f5; padding: 1rem; border-radius: 8px; overflow-x: auto; font-size: 0.875rem;">
          {JSON.stringify(efsdbData, null, 2)}
        </pre>
      </section>
    {/if}
  </main>
</div>

<style>
  :global(body) {
    margin: 0;
  }

  .template-container {
    font-family: system-ui, -apple-system, sans-serif;
    color: #111827;
    background: #f9fafb;
    min-height: 100vh;
  }

  .hero {
    background: #1f2937;
    color: white;
    padding: 4rem 2rem;
    text-align: center;
  }

  .hero h1 {
    margin: 0;
    font-size: 3rem;
    font-weight: 800;
    letter-spacing: -0.025em;
  }

  .subtitle {
    margin-top: 1rem;
    font-size: 1.25rem;
    color: #d1d5db;
  }

  .content {
    max-width: 1000px;
    margin: 0 auto;
    padding: 3rem 2rem;
  }

  .features-grid {
    display: grid;
    grid-template-columns: repeat(auto-fit, minmax(250px, 1fr));
    gap: 1.5rem;
    margin-bottom: 3rem;
  }

  .feature-card {
    background: white;
    padding: 1.5rem;
    border-radius: 0.75rem;
    box-shadow: 0 4px 6px -1px rgba(0, 0, 0, 0.1);
  }

  .feature-card h3 {
    margin-top: 0;
    color: #374151;
  }

  .feature-card p {
    color: #6b7280;
    line-height: 1.5;
    margin-bottom: 0;
  }

  .interactive-section {
    background: white;
    padding: 2rem;
    border-radius: 0.75rem;
    box-shadow: 0 4px 6px -1px rgba(0, 0, 0, 0.1);
    text-align: center;
  }

  .action-btn {
    background: #3b82f6;
    color: white;
    border: none;
    padding: 0.75rem 1.5rem;
    border-radius: 0.5rem;
    font-size: 1rem;
    font-weight: 600;
    cursor: pointer;
    transition: background-color 0.2s;
  }

  .action-btn:hover {
    background: #2563eb;
  }
</style>
